source 'https://rubygems.org'
gem 'cocoapods'
# activesupport-7.1.0 causes the following error: https://app.circleci.com/pipelines/github/mapbox/mapbox-common-ios/698/workflows/41765281-efa2-44f7-ae02-dfeb308224f4/jobs/1891
gem 'activesupport', '7.0.8'
# required if we don't want to bump rails a major, due to error "uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger"
gem 'concurrent-ruby', '1.3.4'
