name: Approve release pr
on:
  pull_request:
    types: opened

jobs:
  approve-release-pull-request:
    if: |
      startsWith(github.head_ref, 'release-v') &&
      startsWith(github.base_ref, 'main') &&
      startsWith(github.event.pull_request.user.login, 'mapbox-github-ci-writer-public-') &&
      github.event.pull_request.user.id == '93400552'
    runs-on: ubuntu-latest
    steps:
      - name: Approve Pull Request
        run: gh pr review $PR --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep then trigger
        run: |
          sleep 30
      - name: Trigger workflow
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $

